#!/bin/bash

app_pattern="$1"
app_cmd="$2"
move_to_desk="$3"

bg_win=$(echo "ibase=16; `wmctrl -l | grep -i "$app_pattern" | cut -c 3-11 | tr a-z A-Z`" | bc)
if [[ -z "$bg_win" ]]; then
    $app_cmd &
    exit 0
fi

active_win=$(xdotool getactivewindow)

if [[ "$active_win" == "$bg_win" ]]; then
    xdotool windowminimize "$active_win"
else
    if [[ "$move_to_desk" == '1' ]]; then 
        xdotool set_desktop_for_window "$bg_win" $(xdotool get_desktop) 
    else
        xdotool set_desktop $(xdotool get_desktop)
    fi
    xdotool windowmap "$bg_win" windowactivate "$bg_win" windowfocus "$bg_win"
    # workaround if initial focus doesn't work
    sleep 0.1
    xdotool windowfocus "$bg_win"  
fi
